# Github action to deploy coverage html to github pages
name: Proxy Everywhere CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install hardhat
        run: npm install --save-dev hardhat
      - name: Run Tests
        run: REPORT_GAS=true npx hardhat test
      - name: Run coverage
        run: npx hardhat coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: coverage
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}